### ISSUE TITLE
The webfont is not work

### ISSUE THREAD

**Issue by shadeed** [shadeed/iShadeed-Blog#2]
In the social block, when I add <i> or <span> tag, the icon appears as a white square
![screen shot 2014-07-02 at 8 58 06 pm](https://cloud.githubusercontent.com/assets/8038659/3466187/d100fb92-027b-11e4-8267-42305c2e91b1.png)

**Comment by aymanfarhat** [comment]
Thats because its not finding the icon files. If you refer to css/flaticon.css notice:

```
@font-face {
         font-family: "Flaticon";
         src: url("flaticon.eot");
         src: url("flaticon.eot#iefix") format("embedded-opentype"),
         url("flaticon.woff") format("woff"),
        url("flaticon.ttf") format("truetype"),
        url("flaticon.svg") format("svg");
        font-weight: normal;
        font-style: normal;
}    
```

It is referring to the font files assuming that they're in the same directory as the current(CSS) file. In reality the font files are on /fonts directory. Relative to this CSS file it would be: ../fonts/flaticon.eot 

../ here means: up one director relative to current file. 

Same thing applies to referencing the other font files in the code block.

**Comment by shadeed** [comment]
Thanks Ayman :)
